stages:
  - build
  - deploy

.build-image: &build-image
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

build-random-image:
  <<: *build-image
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg NPM_TOKEN=$CI_PAT
      --compressed-caching=false
      --cleanup
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:${CI_COMMIT_TAG}
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG !~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/

build-candidate-image:
  <<: *build-image
  script:
    - export TAG="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA-$(date +%s)"
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --build-arg NPM_TOKEN=$CI_PAT
      --compressed-caching=false
      --cleanup
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:${TAG}
      --destination $CI_REGISTRY_IMAGE:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TITLE !~ /^chore\(release\).*\ \[release\]$/

release-version:
  stage: deploy
  image: node:18
  script:
    - git config user.email "${GIT_CI_EMAIL}"
    - git config user.name "${GIT_CI_USER}"
    - npm i standard-version --location=global
    - npm run release -- --no-verify
    - git remote set-url --push origin https://$GIT_CI_USER:$GIT_CI_PASSWORD@gitlab.com/$CI_PROJECT_PATH.git
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
  needs: ['build-candidate-image']
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TITLE !~ /^chore\(release\).*\ \[release\]$/
      when: manual

promote-images:
  stage: deploy
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag ${CI_REGISTRY_IMAGE}:latest $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/
